/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryWorkoutIdRouteImport } from './routes/history.$workoutId'
import { Route as HistoryWorkoutIdEditRouteImport } from './routes/history.$workoutId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryWorkoutIdRoute = HistoryWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryWorkoutIdEditRoute = HistoryWorkoutIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HistoryWorkoutIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRouteWithChildren
  '/progress': typeof ProgressRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRouteWithChildren
  '/history/': typeof HistoryIndexRoute
  '/history/$workoutId/edit': typeof HistoryWorkoutIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/exercises': typeof ExercisesRoute
  '/progress': typeof ProgressRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRouteWithChildren
  '/history': typeof HistoryIndexRoute
  '/history/$workoutId/edit': typeof HistoryWorkoutIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRouteWithChildren
  '/progress': typeof ProgressRoute
  '/history/$workoutId': typeof HistoryWorkoutIdRouteWithChildren
  '/history/': typeof HistoryIndexRoute
  '/history/$workoutId/edit': typeof HistoryWorkoutIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/history/$workoutId'
    | '/history/'
    | '/history/$workoutId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/exercises'
    | '/progress'
    | '/history/$workoutId'
    | '/history'
    | '/history/$workoutId/edit'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/exercises'
    | '/history'
    | '/progress'
    | '/history/$workoutId'
    | '/history/'
    | '/history/$workoutId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ExercisesRoute: typeof ExercisesRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  ProgressRoute: typeof ProgressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$workoutId': {
      id: '/history/$workoutId'
      path: '/$workoutId'
      fullPath: '/history/$workoutId'
      preLoaderRoute: typeof HistoryWorkoutIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$workoutId/edit': {
      id: '/history/$workoutId/edit'
      path: '/edit'
      fullPath: '/history/$workoutId/edit'
      preLoaderRoute: typeof HistoryWorkoutIdEditRouteImport
      parentRoute: typeof HistoryWorkoutIdRoute
    }
  }
}

interface HistoryWorkoutIdRouteChildren {
  HistoryWorkoutIdEditRoute: typeof HistoryWorkoutIdEditRoute
}

const HistoryWorkoutIdRouteChildren: HistoryWorkoutIdRouteChildren = {
  HistoryWorkoutIdEditRoute: HistoryWorkoutIdEditRoute,
}

const HistoryWorkoutIdRouteWithChildren =
  HistoryWorkoutIdRoute._addFileChildren(HistoryWorkoutIdRouteChildren)

interface HistoryRouteChildren {
  HistoryWorkoutIdRoute: typeof HistoryWorkoutIdRouteWithChildren
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryWorkoutIdRoute: HistoryWorkoutIdRouteWithChildren,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ExercisesRoute: ExercisesRoute,
  HistoryRoute: HistoryRouteWithChildren,
  ProgressRoute: ProgressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
